# 数据的基本操作
## 创建向量

In [50]:
import torch

torch.arange(n)操作能够生成一个行向量，这个行向量包含从0开始的前n个整数：

In [51]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

x.shape可以访问向量的形状：

In [52]:
x.shape

torch.Size([12])

x.numel可以访问向量的总个数，即行x列：

In [53]:
x.numel()

12

x.reshape(x,y)可以将张量x变成x行y列的矩阵，而不改变其元素的值：“

In [54]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

可以通过利用-1来自动计算维度：

In [55]:
X = x.reshape(2, -1)
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

我们可以通过torch.zeros((x,y,z))来生成一个全为0的向量：

In [56]:
x = torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

同样，我们也可以通过torch.ones((x,y,z))生成一个全为1的向量：

In [57]:
x = torch.ones((5,6))
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

## 运算
+，-，*，/，**都是按元素运算

In [58]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([2, 2, 2, 2])
# 这两个向量的大小一定要匹配，否则报错
x + y, x - y, x * y, x / y, x ** y

(tensor([3, 4, 5, 6]),
 tensor([-1,  0,  1,  2]),
 tensor([2, 4, 6, 8]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000]),
 tensor([ 1,  4,  9, 16]))

In [59]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

利用torch.cat((x,y), dim=n)能将两个矩阵连结在一起，n表示在第n个方向上连结，即新矩阵的第n个方向的长度为两个旧矩阵长度的和，其他方向上的长度不变

In [60]:
x = torch.arange(12).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

利用 == 可以判断逐个位置判断两个张量在相应位置上的值是否相同

In [61]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量使用sum()方法可以生成一个单元素张量，值为原张量中所有元素的和

In [47]:
x.sum()

tensor(66)

## 广播机制
两个形状不同的张量进行运算后，通过复制行/列使两个张量形状相同后再进行运算：

In [65]:
x = torch.tensor([1, 2, 3]).reshape(1, 3)
y = torch.tensor([1, 2]).reshape(2, 1)
# x复制行，y复制列后两者形状相同
x, y, x + y, x - y, x * y, x / y, x ** y

(tensor([[1, 2, 3]]),
 tensor([[1],
         [2]]),
 tensor([[2, 3, 4],
         [3, 4, 5]]),
 tensor([[ 0,  1,  2],
         [-1,  0,  1]]),
 tensor([[1, 2, 3],
         [2, 4, 6]]),
 tensor([[1.0000, 2.0000, 3.0000],
         [0.5000, 1.0000, 1.5000]]),
 tensor([[1, 2, 3],
         [1, 4, 9]]))

## 索引
第一个元素的索引为0，最后一个元素的索引为-1，可以用[a:b]选择从第a个到第b个（不含）的元素：

In [67]:
x = torch.arange(12).reshape(4,3)
x, x[0], x[-1], x[1:3], x[1:3, 1:2], x[:, 1:2], x[1, :]

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([0, 1, 2]),
 tensor([ 9, 10, 11]),
 tensor([[3, 4, 5],
         [6, 7, 8]]),
 tensor([[4],
         [7]]),
 tensor([[ 1],
         [ 4],
         [ 7],
         [10]]),
 tensor([3, 4, 5]))

除此以外，我们也可以通过指定索引来将元素写入矩阵：

In [68]:
x[1, 2] = 100
x

tensor([[  0,   1,   2],
        [  3,   4, 100],
        [  6,   7,   8],
        [  9,  10,  11]])

我们也可以通过索引所有元素来批量赋值：

In [72]:
x[2: , :] = 114514
x

tensor([[     0,      1,      2],
        [     3,      4,    100],
        [114514, 114514, 114514],
        [114514, 114514, 114514]])

## 节省内存
在Python中，y = x + y 这一操作可能会改变y指向的内存，原因是Python会先计算x + y，为结果分配一个新的内存，再将y指向内存中的新位置：

In [74]:
y = torch.zeros_like(x)
before = id(y)
y = x + y
before == id(y)

False

但是在大部分情况下，我们希望执行原地操作，即在原地址上修改y的值，这时候我们可以采用以下这两种方法：

In [75]:
before = id(y)
y[:] = x + y
before == id(y)

True

In [76]:
before = id(y)
y += x
before == id(y)

True

## 类型转换
要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数：

In [77]:
x = torch.tensor([114514])
x, x.item(), int(x), float(x)

(tensor([114514]), 114514, 114514, 114514.0)