In [1]:
import torch

# 线性代数相关操作
## 矩阵
矩阵转置可以通过.T操作执行，对三维及以上的向量最好不要进行转置操作

In [9]:
A = torch.arange(12,dtype=torch.float32).reshape(3, 4)
A, A.T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  4.,  8.],
         [ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.]]))

.sum除了可以求和以外，还可以用于降维：

In [ ]:
A, A.sum(), A.sum(axis=0), A.sum(axis=1), A.sum(axis=1, keepdim=True), A.sum(axis=[0,1])

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor(66),
 tensor([12, 15, 18, 21]),
 tensor([ 6, 22, 38]),
 tensor([[ 6],
         [22],
         [38]]),
 tensor([[66]]))

通过.mean函数我们可以求出矩阵中所有元素的平均值：

In [10]:
A.mean(), A.sum()/ A.numel()

(tensor(5.5000), tensor(5.5000))

同样，计算平均值的函数也可以沿指定轴降低维度：

In [11]:
A.mean(axis = 0), A.sum(axis=0)/ A.shape[0]

(tensor([4., 5., 6., 7.]), tensor([4., 5., 6., 7.]))

如果我们想沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。

In [12]:
A.cumsum(axis=0), A.cumsum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  6.,  8., 10.],
         [12., 15., 18., 21.]]),
 tensor([[ 0.,  1.,  3.,  6.],
         [ 4.,  9., 15., 22.],
         [ 8., 17., 27., 38.]]))

## 点积
两个向量进行点积运算可以使用torch.dot(x,y)

In [18]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([4, 5, 6, 7], dtype=torch.float32)
torch.dot(x, y), torch.sum(x * y)

(tensor(60.), tensor(60.))

## 矩阵-向量积
我们可以通过torch.mv(A,x)来计算矩阵A和向量x的乘积，注意：A的列维数（沿轴1的长度）必须与x的维数（其长度）相同

In [19]:
torch.mv(A,x)

tensor([ 20.,  60., 100.])

## 矩阵乘法
我们可以通过torch.mm(A,B)来计算矩阵A和矩阵B的乘积：

In [20]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.]])

# 范数
我们可以通过.norm来计算张量的L_2范数：

In [25]:
a = torch.tensor([3,-4], dtype=torch.float32)
b = torch.ones((4,9), dtype=torch.float32) # 矩阵也可以这么计算
a.norm(), b.norm()

(tensor(5.), tensor(6.))

我们可以通过结合绝对值和求和来计算张量的L_1范数

In [24]:
torch.abs(a).sum(), torch.abs(b).sum()

(tensor(7.), tensor(36.))